#!/bin/sh
if [ $# -eq 0 ]
then
echo "Error -Number missing from command line "
echo "Syntax : $0 number "
echo "multiple table "
exit 1
fi
#
n=$1
#
for i in 1 2 3 4 5 6 7 
do
echo "$n * $i =`expr $i \* $n`"
done


